require("aeslua");
ss = "1234123412341234";
print(ss);
print(string.len(ss));
aa = aeslua.encrypt("password",ss);
print(aa);
print(string.len(aa));
bb = aeslua.decrypt("password",aa);
print(bb);
print(string.len(bb));
